### PR TITLE
Fixed dependencies

### PR DESCRIPTION
**Pull request by Binero**
Stopped compiling when libc updated. Set it to use an older version.

### CODE REVIEW

**Comment by csherratt** [comment]
This repo is depcrated, it has been moved here https://github.com/gfx-rs/gfx/tree/master/src/backend/gl

**Comment by Binero** [comment]
That isn't true yet. Cargo based projects still use this one.

**Comment by kvark** [comment]
@Binero well, for one, version here is 0.4.0, while crates io has [0.6.1](https://crates.io/crates/gfx_device_gl). This repo has been deprecated for quite a while already.

**Comment by kvark** [comment]
@csherratt I suppose we can actually kill these deprecated repositories already?

**Comment by bvssvni** [comment]
I agree. Remember to check the urls on crates.io, though.

**Pull request closed without merging**
